# Generated by Django 5.0.6 on 2024-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_details_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='class_name',
            field=models.CharField(default='SOME STRING', max_length=5),
        ),
    ]
