# Generated by Django 5.0.6 on 2024-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_details_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='fee_due',
            field=models.IntegerField(default=0),
        ),
    ]
