# Generated by Django 5.0.6 on 2024-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_details_fee_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='fee_due',
            field=models.IntegerField(default=1000),
        ),
    ]
