# Generated by Django 5.0.6 on 2024-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
