# Generated by Django 5.0.6 on 2024-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(default='add_answer', max_length=200),
        ),
        migrations.AddField(
            model_name='questions',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
