# Generated by Django 5.0.6 on 2024-05-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_questions_answer_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
