# Generated by Django 5.0.6 on 2024-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
