# Generated by Django 5.0.6 on 2024-05-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_questions_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.questions')),
                ('student_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=15)),
                ('student_phone', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='count',
        ),
    ]
