# Generated by Django 5.0.6 on 2024-05-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_studentmarks_remove_questions_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='id',
            new_name='username',
        ),
    ]
