# Generated by Django 5.0.6 on 2024-05-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_id_studentmarks_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
