# Generated by Django 5.0.6 on 2024-05-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_details_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('std_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.details')),
            ],
        ),
    ]
